#!/bin/bash

# Run this script in the Docker container when you first clone the project

# Create the venv
python3 -m venv $DOCKER_APP_PATH/server/.python-venv

# Activate the virtual environment
source $DOCKER_APP_PATH/server/.python-venv/bin/activate

# Install the Python dependencies
python3 -m pip install -r $DOCKER_APP_PATH/server/dependencies.txt

# Install the NodeJS dependencies
cd $DOCKER_APP_PATH/client && npm i --cache /tmp/.npm-cache