name: Deploy to Dokku

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Dokku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        run: |
          echo "Deploying to Dokku server..."
          
          echo ${{ secrets.FRONTEND_ENV }} | xargs ssh -o StrictHostKeyChecking=no dokku@${{ secrets.DOKKU_HOST }} config:set --no-restart qview3d-frontend > /dev/null
          echo ${{ secrets.BACKEND_ENV }} | xargs ssh -o StrictHostKeyChecking=no dokku@${{ secrets.DOKKU_HOST }} config:set --no-restart qview3d-backend > /dev/null
          
          git remote add qview3d-frontend dokku@${{ secrets.DOKKU_HOST }}:qview3d-frontend
          git remote add qview3d-backend dokku@${{ secrets.DOKKU_HOST }}:qview3d-backend
          
          git push qview3d-frontend main --force
          git push qview3d-backend main --force
        env:
          GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
          SSH_AUTH_SOCK: $SSH_AUTH_SOCK
